package deu.hms.manageinfo;

import deu.hms.reservation.BookingInfo;
import deu.hms.reservation.FileManagement;
import deu.hms.reservation.ReservationManagementJFrame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyunwoo
 */
public class HotelStatsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SettlementJFrame
     */
    
    private ReservationManagementJFrame reservationManager = new ReservationManagementJFrame();
    
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private String startDate;
    private String endDate;
    private int startDateValue = 0;
    private int endDateValue = 0;
    
    public String getStartDate() {
        
        startDate = dateFormat.format(inquiryStartDateChooser.getDate());
        
        return startDate;
    }
    
    public String getEndDate() {
        
        endDate = dateFormat.format(inquiryEndDateChooser.getDate());
        
        return endDate;
    }
    
    public void setStartDateValue(String startDate) {
        
        startDateValue = 0;
        
        String[] dateValues = startDate.split("-");
        
        for (int i = 0; i < dateValues.length; ++i) {
            
            startDateValue += Integer.parseInt(dateValues[i]);
        }
    }
    
    public void setEndDateValue(String endDate) {
        
        endDateValue = 0;
        
        String[] dateValues = endDate.split("-");
        
        for (int i = 0; i < dateValues.length; ++i) {
            
            endDateValue += Integer.parseInt(dateValues[i]);
        }
    }
    
    public HotelStatsJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("통계");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();
        inquiryStartDateChooser = new com.toedter.calendar.JDateChooser();
        inquiryEndDateChooser = new com.toedter.calendar.JDateChooser();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        inquiryButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "투숙 인원", "점유율", "객실 수익", "식품 수익"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statsTable);

        fromLabel.setText("부터");

        toLabel.setText("까지");

        inquiryButton.setText("조회");
        inquiryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiryButtonActionPerformed(evt);
            }
        });

        jButton1.setText("닫기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inquiryStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inquiryEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toLabel)
                .addGap(18, 18, 18)
                .addComponent(inquiryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inquiryStartDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inquiryEndDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(toLabel)
                                .addComponent(inquiryButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inquiryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiryButtonActionPerformed
        // TODO inquiryStartDateChooser~inquiryEndDateChooser
        loadStatsData();
    }//GEN-LAST:event_inquiryButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private ArrayList<Integer> hotelStats() {
        
        ArrayList<Integer> hotelStatsArray = new ArrayList<>();
        int numberOfGuests = 0;
        int roomRevenue = 0;
        int hotelOccupancy = 0;
        int foodRevenue = 0;
        
        String[] inputCheckInDateArray = splitDateByDash(getStartDate());
        String[] inputCheckOutDateArray = splitDateByDash(getEndDate());
        String[] loadCheckInDateArray;
        String[] loadCheckOutDateArray;
        
        Date inputCheckInDate = new Date(Integer.parseInt(inputCheckInDateArray[0]) - 1900, 
                                    Integer.parseInt(inputCheckInDateArray[1]) - 1, 
                                    Integer.parseInt(inputCheckInDateArray[2]));
        Date inputCheckOutDate = new Date(Integer.parseInt(inputCheckOutDateArray[0]) - 1900, 
                                    Integer.parseInt(inputCheckOutDateArray[1]) - 1, 
                                    Integer.parseInt(inputCheckOutDateArray[2]));
        Date loadCheckInDate;
        Date loadCheckOutDate;
        
        ArrayList<BookingInfo> bookingInfo;
        try {
            FileManagement fileMgmt = new FileManagement();
            fileMgmt.readBookingFileData(reservationManager.getFilePath());
            fileMgmt.splitBookingFileData();
            bookingInfo = fileMgmt.returnBookingInfo();
            
            for (int i = 0; i < bookingInfo.size(); ++i) {
                
                loadCheckInDateArray = splitDateByDash(bookingInfo.get(i).getCheckInDate());
                loadCheckOutDateArray = splitDateByDash(bookingInfo.get(i).getCheckOutDate());
                loadCheckInDate = new Date(Integer.parseInt(loadCheckInDateArray[0]) - 1900, 
                                            Integer.parseInt(loadCheckInDateArray[1]) - 1,
                                            Integer.parseInt(loadCheckInDateArray[2]));
                loadCheckOutDate = new Date(Integer.parseInt(loadCheckOutDateArray[0]) - 1900, 
                                            Integer.parseInt(loadCheckOutDateArray[1]) - 1,
                                            Integer.parseInt(loadCheckOutDateArray[2]));
                
                if (!(inputCheckOutDate.before(loadCheckInDate) || inputCheckInDate.after(loadCheckOutDate))) { // 지정한 기간에 포함되면
                    numberOfGuests += Integer.parseInt(bookingInfo.get(i).getNumberOfGuests());
                    
                    if (bookingInfo.get(i).getCheckInStatus().equals("예약") || 
                            bookingInfo.get(i).getCheckInStatus().equals("체크인")) { // 지정한 기간에 예약된 상태거나 체크인 상태면
                        
                        ++hotelOccupancy; // 호텔의 방이 100개이므로 점유율은 해당 조건인 방 개수와 같다.
                    }
                    
                    roomRevenue += Integer.parseInt(bookingInfo.get(i).getCostOfStaying());
                }
            }
            
            File file = new File(System.getProperty("user.dir") + "/order_list.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            String[] columns;
            
            while ((line = br.readLine()) != null) {
                
                columns = line.split("\t");
                String[] loadDateArray = splitDateBySlash(columns[0]);
                
                Date loadDate = new Date(Integer.parseInt(loadDateArray[0]) - 1900, 
                                        Integer.parseInt(loadDateArray[1]) - 1,
                                    Integer.parseInt(loadDateArray[2]));
                
                boolean isInclude = inputCheckOutDate.after(loadDate) &&
                                    inputCheckInDate.before(loadDate);
                if (isInclude) {
                    
                    foodRevenue += Integer.parseInt(columns[5]);
                }
            }
            br.close();
            
            hotelStatsArray.add(numberOfGuests);
            hotelStatsArray.add(hotelOccupancy);
            hotelStatsArray.add(roomRevenue);
            hotelStatsArray.add(foodRevenue);
            
        } catch (IOException e) {
        }
        
        return hotelStatsArray;
    }
    
    public String[] splitDateByDash(String date) {
        
        String[] dateValues = date.split("-");
        
        return dateValues;
    }
    
    public String[] splitDateBySlash(String date) {
        
        String[] dateValues = date.split("/");
        
        return dateValues;
    }
    
    private int calcOrderListDateValue(String date) {
        
        int dataValue = 0;
        String[] dateValues = date.split("/");
        
        for (int i = 0; i < 3; ++i) {
            
            dataValue += Integer.parseInt(dateValues[i]);
        }
        
        return dataValue;
    }
    
    private void loadStatsData() {
        
        ArrayList<Integer> hotelStatsArray = hotelStats();
        DefaultTableModel statsTableModel = (DefaultTableModel) statsTable.getModel();
        
        // 데이터를 담을 2차원 배열 생성
        Object[][] data = new Object[hotelStatsArray.size()][4];
        
        // 2차원 배열에 데이터 채우기
        for (int i = 0; i < hotelStatsArray.size() / 4; ++i) {
            data[i][0] = hotelStatsArray.get(i);
            data[i][1] = hotelStatsArray.get(i + 1);
            data[i][2] = hotelStatsArray.get(i + 2);
            data[i][3] = hotelStatsArray.get(i + 3);
        }
        // 테이블 모델 업데이트
        statsTableModel.setDataVector(data, new Object[]{
            "투숙 인원", "점유율", "객실 수익", "식품 수익"
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelStatsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelStatsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelStatsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelStatsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelStatsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromLabel;
    private javax.swing.JButton inquiryButton;
    private com.toedter.calendar.JDateChooser inquiryEndDateChooser;
    private com.toedter.calendar.JDateChooser inquiryStartDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable statsTable;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
